pub const AUTHENTICATION_SUCCESS: &str = "AUTHENTICATION_SUCCESS";
pub const USER_REGISTERED: &str = "USER_REGISTERED";
pub const RESOURCE_CREATED: &str = "RESOURCE_CREATED";
pub const OPERATION_SUCCESS: &str = "OPERATION_SUCCESS";
pub const VALIDATION_FAILED: &str = "VALIDATION_FAILED";
pub const NOT_FOUND: &str = "NOT_FOUND";
pub const INTERNAL_ERROR: &str = "INTERNAL_ERROR";
